### ISSUE TITLE
Peer messaging. Investigate possible implementations. [time-boxed]

### ISSUE THREAD

**Issue by marcosnc** [decentraland/catalyst#100]
In the next quarter we need to provide services that allow our users to chat between them.
The objective of this task is to explore possible implementations for that feature.

Besides the current client allows the users to chat, it's limited to the peers they have around, the so called "whispering".
The new feature should our users to send private messages to their friends, even when they are offline. Those messages should be stored in a secure way (no one besides the sender and the receiver should be able to see them) and delivered to the destination peer when it get back online.

As part of this investigation we should take a look at matrix.org

**Comment by marcosnc** [comment]
I've made some investigation on matrix.org and think it's a good project to base our messaging system on.
Based on that I think we should perform the following tasks in order to provide the services to support our messaging system:

1) Add a matrix Synapse server to our catalyst bundle
   See: https://github.com/matrix-org/synapse

2) Ensure all synapse servers inside the catalyst network can see each other

3) Implement an authentication mechanism using signed message (reusing decentraland crypto)
   See:
     https://github.com/matrix-org/synapse/blob/master/docs/password_auth_providers.md
     https://github.com/matrix-org/synapse/blob/master/docs/saml_mapping_providers.md
     https://matrix.org/docs/spec/application_service/r0.1.2
     https://matrix.org/docs/spec/identity_service/r0.3.0

4) Implement a mini cliente in the kernel
   See:
     https://github.com/matrix-org/matrix-js-sdk/blob/develop/examples/node/app.js

**Comment by nchamo** [comment]
Closing, implemented on https://github.com/decentraland/matrix-client/
