### ISSUE TITLE
Profile deployments validation

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1011]
Define a new ADR with timestamp to validate more precisely the profile deployments.

Validate when deploying a profile that the wearables are valid URNs and are owned by the address

**Comment by agusaldasoro** [comment]
Also, in Access Checker validate that:

```
if(profile.hasClaimedName && !(profile.name in claimedNames)) then throw
```

**Comment by agusaldasoro** [comment]
Should we allow to support more than one avatar per profile? Changing that may imply a huge breaking change anyway

**Comment by marianogoldman** [comment]
Fixed
