### ISSUE TITLE
Auto release with conventional commits

### ISSUE THREAD

**Issue by agusaldasoro** [decentraland/catalyst#1036]
- Use Semver for the releases
- Use [conventional commits](https://github.com/decentraland/standards/blob/master/standards/git-usage.md#allowed-type-values) to define if the code should be part of a patch, minor or major version
- When the code is merged into the main branch, automatically publish a new Catalyst image if the convention says that the version is a patch or minor. For this: validate the commit message to block the merge of the PR. Use the lib: https://github.com/semantic-release/npm#readme

**Comment by menduz** [comment]
You can use semantic release + github releases to not touch any of the pipeline https://github.com/semantic-release/github
