### ISSUE TITLE
After teleporting populated scene, we don't see other avatars until we change realms again

### ISSUE THREAD

**Issue by pravusjif** [decentraland/catalyst#1037]
I think this is happening every time we teleport to a populated scene, for example the ICE Poker Stronghold or Wonder Mine.

If we change to another realm and come back to the original one, people start appearing after some time.

https://user-images.githubusercontent.com/1031741/161844815-6ebf842c-0ef3-4225-a1cb-a609587e6da7.mp4

**Comment by menduz** [comment]
Pravus, could you confirm if it also happens with this PR? https://github.com/decentraland/kernel/pull/261

**Comment by pravusjif** [comment]
> @pravusjif , could you confirm if it also happens with this PR? [decentraland/kernel#261](https://github.com/decentraland/kernel/pull/261)

I confirm the problem is fixed in that PR, nice job!
