### ISSUE TITLE
Realm Scoring: Design Improvements

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1075]
The logic on the realm scoring should be improved to take into consideration more variables in order for a server to be more eligible. As with the current model, any added variable needs to be modifiable through Feature Flags so that they can be changed in case of need without a release or a reboot of the server.
Some aspects that should be considered:  
- Resources: if a server is with the CPU at 90%, don't add more load to that server, same for memory 
- Catalyst version: if the version of the node is behind the network, it should be less eligible 
- If the URL has specific coordinates, the concentration of peers at the location could be considered 
- Healthy state of the server, check if the server needs to be too unhealthy if for some reason is left behind on the synchronization.  

This behavior should be in the BFF and not in Kernel. Each catalyst should be able to override the feature flags values.

**Comment by agusaldasoro** [comment]
RFC: https://adr.decentraland.org/adr/ADR-145

**Comment by aleortega** [comment]
Technical draft can be found [here](https://docs.google.com/document/d/1bCM43qQ4PpMmbtxdCj-hovLgBDWdmfY8ARHzVs1AdRI/edit#heading=h.r70cf362tfwn). Please request access to document if you don't have.
