### ISSUE TITLE
Host a IPFS node

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1130]

**Comment by juanscolari** [comment]
IPFS-go node hosted on `https://peer-historical.decentraland.org/ipfs`. Using the catalyst-owner branch: `feat/historic-ipfs`

Example of a file served by the gateway: https://peer-historical.decentraland.org/ipfs/Qmc11wSPbP3ifYYkPybCbWFhe7yz6iCZYkQtTJ8W1pTmu3
