### ISSUE TITLE
Modify lambdas to get entities always from POST /content/entities/active endpoint

### ISSUE THREAD

**Issue by agusaldasoro** [decentraland/catalyst#1160]
The lambdas code is requesting a deprecated endpoint (`GET /content/entities/{entityType}?id=ids`) in the content server to retrieve:
- profiles
- entities by id
- entities by pointer

It must use the endpoint `POST /entities/active` with the params in the body.

**Comment by aleortega** [comment]
Completed on https://github.com/decentraland/catalyst-client/pull/243
