### ISSUE TITLE
i cant see anyone in decentraland

### ISSUE THREAD

**Issue by celteq** [decentraland/catalyst#1192]
### What happened?

i cant see anyone in decentraland, please fixed it

### Steps to reproduce

i cant see and dont see everyone, please help me

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

windows 10 pro

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671) 512MB

### RAM

16.0 gb

### Kernel Version

1.0.0-1592770279.commit-473692f

### Unity Version

1.0.22656-20211217163527.commit-f7c808f

### Realm

dg

### NameTag

CELTEQ#8343

**Comment by agusaldasoro** [comment]
This issue doesn't have the necessary information to reproduce it. Closing it
