### ISSUE TITLE
QA NFT Emotes

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1208]
- [x] Deploy a profile with NFT Emote (sync with dApps) and add  Keystrokes settings for the emotes  
     - Tested deploying profile with owned emotes (disabling only signature validation).
- [x] Get a profile with owned NFT Emote. Keystrokes should be retrieved from the profile settings.   
- [x] Get a profile with sold/give away NFT Emote. Expected result: NFT emote should be removed from the profile. 
   - Tested deploying profile with NOT owned emote disabling validations.
- [x] Get NFT by owner with sold/give away NFT Emote. Expected result: NFT emote should be removed from the profile.
     - Not tested. Don't have real ownership of an Emote to test it. Recommend to do that to people with access to Emotes.
- [x] Get a profile with old emotes (saved as Wearables) are NOW shown in `emotes` property and NOT in `wearables` property.
- [x] Forbid deploying profile with base avatars in `emotes`?
- [x] Validate `slot` is not repeated in `emotes`.
    - Not needed.
- [x] Validate profiles items are owned and in right place (i.e. emotes in `emotes`, wearables in `wearables`). If difficult, create issue.
    - Not necessary.
- [x] Double check old emotes in `wearables` come in order and there are `nulls` (or what?) between them.
     - They are saved without order. So we preset from 0 to 9 in the order of appearance.

**Comment by pedrotambo** [comment]
- [ ] Deploy a profile with NFT Emote (sync with dApps) and add  Keystrokes settings for the emotes  
- [ ] Get a profile with owned NFT Emote. Keystrokes should be retrieved from the profile settings.   
- [ ] Get a profile with sold/give away NFT Emote. Expected result: NFT emote should be removed from the profile. 
   - Deployed profile with NOT owned emote disabling validations.
- [ ] Get NFT by owner with sold/give away NFT Emote. Expected result: NFT emote should be removed from the profile. 
- [x] Get a profile with old emotes (saved as Wearables) are NOW shown in `emotes` property and NOT in `wearables` property.
- [ ] Forbid deploying profile with base avatars in `emotes`?
