### ISSUE TITLE
Cannot hear or voice chat with other on the Parcel

### ISSUE THREAD

**Issue by soq2000** [decentraland/catalyst#1274]
When we are in the same land , Pressing T and talk  (we can see the animation of the mic's signal) but no one can hear. If we click on leave voice chat then rejoin, other can hear for a randomly long period. Then thing happens again. No one can hear...
![image](https://user-images.githubusercontent.com/13979561/189519575-d0b56c47-cda0-4d43-b3eb-6e9215ca08e5.png)

**Comment by hugoArregui** [comment]
I think we resolved this issue via discord, please reopen if still happens, thanks!
