### ISSUE TITLE
Extended Passport Tech Assessment

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1302]
A New Passport view is being developed by the Explorer. 
This view will require storing information in the profile entity and retrieving things as collectibles to be displayed, as well as being able to block, add as a friend or initiate a chat.

**Comment by pentreathm** [comment]
https://www.notion.so/decentraland/Platform-Technical-Assessment-8af84179462e4acea066ac90a882f1fe

**Comment by menduz** [comment]
@pentreathm can you cross-post it here for traceability and transparency?

**Comment by pentreathm** [comment]
Cross-Posting the Technical Assessment: 

## Requirements

The applicable requirements from the Catalyst point of view:

1. Intro of a user: 
Use the "**description"** field from profiles to use in the "Intro" section or create a new one if it is different from the "description".

2. Block/Unblock users:
Use the "**blocked"** field from profiles to see/report blocked users.

3. Equipped wearables:
Take the information from the profile. There are the equipped wearables, emotes and the current name.

4. Collectibles: wearables/emotes/names/lands:
For the wearables and emotes there are two available endpoints **/wearables-by-owner** and **/emotes-by-owner** that can be used for that. It will be necessary to create **/names-by-owner** and **/lands-by-owner** endpoints with similar behavior.

## Performance

To load a passport, first, there will be made 5 requests to a Catalyst (lambdas):

1. /profiles
2. /wearables-by-owner
3. /emotes-by-owner
4. /lands-by-owner
5. /names-by-owner

Once this information is obtained, to display wearables and emotes it will be needed a couple of requests per each emote/wearable to download its image/thumbnail to be shown. This does not scale because some users have more than 1k NFTs. So the explorer should implement a lazy loading mechanism (for image/thumbnail) as the user browses the collectibles.

All except /profiles are expensive requests. Internally, from 2 to 5 they make queries to The Graph to check owned NFTs urns and then to the content server to get the definitions. Currently, 2 and 3 are not paginated, so making a query for a user that owns more than 1k wearables would be considerably heavy. Also, sometimes queries to The Graph are slow. So to improve this situation the endpoints from 2 to 5 could be paginated.

## Estimate

MVP
The requirements are not blocking to start the client-side development

- Implement /lands-by-owner and /names-by-owner **~2weeks**

Performance Improvements 

- Add pagination to the existing endpoints
- /lands-by-owner and /names-by-owner can be cached.
- Push kernel/explorer to do thumbnails lazy loading



# Suggestions:  

@menduz 
Due to the complexity of those calls being executed from kernel/renderer we should take a different path for all new development: One request to rule them all. I propose a /passport/:address method that returns all the needed information, that endpoint can be called from the Renderer directly, removing dependencies and coupling with Kernel and also providing enough isolation of concerns to evolve independently from other endpoints

Can we unify all the calls into a single /passport/:address ? that way we would reduce a ton of complexity on the renderer/kernel side of things and only perform ONE call   

@pentreathm 
We can also leverage the BFF and implement the mentioned endpoint using a WebSocket to communicate the client and the server and thus avoid having a public contract and backward compatibility challenges as the feature evolves.

**Comment by pentreathm** [comment]
Follow implementation here 
https://github.com/decentraland/explorer-bff/issues/185

**Comment by m3taphysics** [comment]
@pentreathm could you tell me or expand the technical assessment to include the retrieval of the friends count, friends list and mutual friends list? Will this be included in the new /passport/profile endpoint implementation?

**Comment by pentreathm** [comment]
@m3taphysics that information doesn't come from the Catalyst nodes, it is on the Matrix servers (the ones that manage the chat & friendships) so it is out of the scope of this technical assessment. 
@moliva did you do a tech assessment for this feature?

**Comment by moliva** [comment]
Hey there - Mutual friends is something we cannot provide currently and are working for a solution in the future.
