### ISSUE TITLE
Fix bug of deleted files when garbage collecting profiles

### ISSUE THREAD

**Issue by agusaldasoro** [decentraland/catalyst#1370]
### Description

Some profile deployments are being done with the `contents` field empty, as they are deployed using the method `buildEntityWithoutNewFiles` from the [Catalyst Client](https://github.com/decentraland/catalyst-client/blob/f2b77cfdb83f8b60017a9d250f14aeb3a28b6c39/src/utils/DeploymentBuilder.ts#L109) and sending the `hashesByKey` param empty.
This results in making a deployment without referenced files, so when Garbage Collection runs it deletes files that shouldn't be, leaving the Content Servers in an inconsistent state.

### ADR

https://github.com/decentraland/adr/pull/158

### Issues

To fix this, the following tasks must be done:

- [x] https://github.com/decentraland/catalyst/pull/1376 Create a migration for affected entities: run a migration that checks all the hashes referenced in the snapshots metadata profiles and then downloads the missing files and store them in the content files table of the database
- [x] https://github.com/decentraland/content-validator/pull/148 Add a new validation in [Content Validator](https://github.com/decentraland/content-validator) which ensures that all profiles have the files `face.png` and `body256.png` in the content field
- [x] https://github.com/decentraland/decentraland-dapps/issues/323 Update [Decentraland dApps](https://github.com/decentraland/decentraland-dapps/blob/de92b4cc4ac701e6f51a92802bbaa27fdda22897/src/lib/entities.ts#L94) to send the necessary `hashesByKey` when making a deployment with the Catalyst Client using the `buildEntityWithoutNewFiles`. An example of that can be found at [Kernel](https://github.com/decentraland/kernel/blob/3eb437a4a956abaa4dfd287eb5c85c0d5b1d9112/packages/shared/profiles/sagas.ts#L452)

**Comment by marianogoldman** [comment]
Fixed merged. deployed in Catalyst 6.0.5.
After updating to 6.0.5, a script need to be run to fix any deployments that might not be referencing their files.
