### ISSUE TITLE
[security] Allow a client to challenge the server to know it's being run by the owner

### ISSUE THREAD

**Issue by abarmat** [decentraland/catalyst#15]
**Context**
There is a list of 3 servers in the Node Registry: [A, B, C]

Each Node is registered using the following structure:
>     struct Katalyst {
>         bytes32 id;
>         address owner;
>         string domain;
>     }
> 

Each Client uses the above information to connect to the servers as they see fit.

**Problem**
Though any Client can trust that each NodeRegistry entry was approved by the DAO, the server they connect to can be impersonated in different ways. If Server B is poisoned it might start returning bogus data.

**Proposal**
Maybe it is a good idea to allow for clients to challenge the servers and ensure they are who they say.

This can maybe be done by: 
A) The Client sending a `/challenge` request with a particular random message.
B) The Server signing the message with the corresponding address PrivateKey and sending it back to the client.
C) The Client verifies that the message was signed by the owner Key.

Note:
To avoid exposing the owner private key having it sit on a server, a different challenge private key could be used.

**Comment by moliva** [comment]
HTTPS is mandatory as of today. Client needs servers to work on secure HTTP and will refuse expired certificates. Closing the issue.
