### ISSUE TITLE
Fix Lamb2 Profile cache invalidation

### ISSUE THREAD

**Issue by pedrotambo** [decentraland/catalyst#1598]
The lamb2 profile cache might have invalid profiles cached for some minutes. A client requests a profile to Lamb2, which gets and caches it. Then a new profile deployment is made to the content server, but lamb2 still has the previous one. Request the same profile again to lamb2 within the 5 minutes caching time will result in retrieving an un-updated profile

**Comment by hugoArregui** [comment]
I think this is done since the lamb2 caches only applies to NFTs
