### ISSUE TITLE
Add support for S3 storage

### ISSUE THREAD

**Issue by nchamo** [decentraland/catalyst#187]
As of now, content files can only be stored on the local filesystem. We already have an interface `ContentStorage`, so we would only need to implement it, and add some environment configuration for the S3 bucket to be set.

This change could add a new way for catalyst owners to create an inconsistent state. We may need to add a check during startup to make sure that all files that are supposed to be present on the storage, actually are. If this check fails, then the content server should show the appropriate error message and cancel the startup.

**Comment by agusaldasoro** [comment]
This change is de-prioritized.
