### ISSUE TITLE
[Investigation] What happens when the same entity is deployed in different servers?

### ISSUE THREAD

**Issue by nchamo** [decentraland/catalyst#191]
Content servers don't require any type of consensus. Each deployment is shared and validated by all servers, and there is no concept similar to "double spending". However, there is a possibility that the same entity could be deployed in two or more different servers at the same time. 

This should have no effect other than having the same entity with different `originTimestamp` and `originServerUrl`, but we need to make sure that is the case.

**Comment by agusaldasoro** [comment]
The concepts of `originTimestamp` and `originServerUrl` do not longer exist.
