### ISSUE TITLE
Upgrade to IPFSv2 hashing algorithm

### ISSUE THREAD

**Issue by menduz** [decentraland/catalyst#200]
# Upgrade to IPFSv2 hashing algorithm

Nowadays the content hashing algorithm is not 1:1 with IPFS. It is an ad-hoc hashing. The hashes are prefixed with `Qm` and have the same encoding of IPFSv1 hashes, but those hashes are not compatible.

We should support the new IPFSv2 hashes (prefixed with `bafy` instead of `Qm`) to enable integration with IPFS and to leverage decentralized and free CDN solutions like Cloudflare IPFS, and to enable other use cases like synchronization cheap P2P between brand new nodes without exhausting bandwidth from specific content servers.

Example link: https://cloudflare-ipfs.com/ipfs/bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/ 

## Caveats
* The content (as it is deployed today) can’t change. It is already signed, indexed and stored using the ad-hoc hashing algorithm (`Qm` prefix). To maintain backward compatibility, every hash starting with `Qm` will be assumed as legacy.
* The CLI should also implement this change, it may be under a flag to test at the beginning. To progressively test the implementation.
* The explorer may have hardcoded logic for the `Qm..` hashes. An assessment would be required.
So does the builder.

- [ ] Add support for both hashes (`Qm` and `bafy`) in catalysts.
- [ ] Add beta support in CLI, behind a flag, for internal testing.
- [ ] Run internal tests in .zone and verify synchronization works correctly.
- [ ] Set up plan for rollout keeping both hashes
- [ ] Define deprecation date for old hashes (about 1/2 month from release)

**Comment by nchamo** [comment]
Just as a note, there is a npm package called [ipfs-only-hash](https://www.npmjs.com/package/ipfs-only-hash) that calculates the v1 hash version of a file. We need to figure out if there is something similar for v2.

**Comment by menduz** [comment]
```typescript
const x = require("ipfs-only-hash");

export function cid(buffer: Uint8Array): Promise<string> {
  return x.of(buffer, { cidVersion: 1 }); // default version is 0
}
```

That does the trick
