### ISSUE TITLE
Add some documentation about content server APIs

### ISSUE THREAD

**Issue by nchamo** [decentraland/catalyst#202]
We have a many different endpoints exposed by the content server. However, they are not documented anywhere. It's a pity, because there is a lot of information that could be used for many different use cases.

We need to write this documentation, and expose it in a way that the community can read it, and use it. It might make sense to add it to https://docs.decentraland.org/

**Comment by agusaldasoro** [comment]
The current documentation for Content Server API is in https://github.com/decentraland/catalyst/blob/master/docs/content-server-api/CONTENT_SERVER_API.md

**Comment by agusaldasoro** [comment]
This issue is closed and deployed in https://decentraland.github.io/catalyst-api-specs/
