### ISSUE TITLE
Support to fetch more than one profile in /profile lambda

### ISSUE THREAD

**Issue by agusaldasoro** [decentraland/catalyst#246]
Right now, our /profile lambda takes an ethAddress, fetches the profile from the content server, and sanitizes its name by querying the-graph. This last action is performed to verify whether the current name is actually an NFT or not. A cache has been added to avoid querying the same values more than once in https://github.com/decentraland/catalyst/issues/243

Anyway, a bigger improvement would be to add support to fetch more than one profile at a time. This would allow the explorer to avoid many requests, and at the same time we could group name queries to the-graph into one

**Comment by nchamo** [comment]
Small comment. If we allow fetching for multiple profiles, the endpoint should probably be called `/profiles`

**Comment by nchamo** [comment]
Done in https://github.com/decentraland/catalyst/pull/249
