### ISSUE TITLE
Add versioning to Catalyst

### ISSUE THREAD

**Issue by agusaldasoro** [decentraland/catalyst#348]
We are currently using commit sha with the latest tag to checkout the versions from the catalyst.

We need to use semver, so we could use the same approach used in Catalyst-Client and in Catalyst-Commons which is:

Use oddish github action to:
- Create a new version with every commit to master branch (with the next tag) and push it to docker.
- Publish every tag in Docker (this will allow us to test behaviour that is work in progress).
- When a release is done, then the new version is uploaded to Docker with the corresponding tag and pointing to latest.

**Comment by agusaldasoro** [comment]
It has been added the hardcoded version of the catalyst to the status endpoint in: https://github.com/decentraland/catalyst/pull/326

**Comment by nchamo** [comment]
Fixed by https://github.com/decentraland/catalyst/pull/363
