### ISSUE TITLE
Investigate deny-list performance

### ISSUE THREAD

**Issue by marcosnc** [decentraland/catalyst#420]
As part of the performance analysis we identified a potential problem in the query used to filter the results when applying the deny-list.
As an emergency action we disabled the deny-list temporarily (see https://github.com/decentraland/catalyst/pull/419) but we need to re-enable it without compromising performance.

We discovered that the query used to check the deny-list may grow unbounded and that may impact in the correct behaviour of the system.
An instance of this query is attached to the issue.

[deny-list-query.txt](https://github.com/decentraland/catalyst/files/6142293/deny-list-query.txt)

**Comment by agusaldasoro** [comment]
The deny-list has been re-enabled with a few performance improvements.
