### ISSUE TITLE
Analyse why the number of file descriptors of the content server almost always goes up

### ISSUE THREAD

**Issue by marcosnc** [decentraland/catalyst#423]
![image.png](https://images.zenhubusercontent.com/5dc174a011dec50001486869/128bc72a-7cba-4a3b-9e34-f97b0c6df0a2)

https://github.com/decentraland/catalyst/blob/6de9a58ef41008917d95fa258ea6b552ee151d45/content/src/controller/Controller.ts#L231 how are we closing the stream and file descriptor after sending the response?

a possible solution https://github.com/pillarjs/send/blob/master/index.js#L800-L804

![image.png](https://images.zenhubusercontent.com/5dc174a011dec50001486869/e546181d-7dbf-44d0-8029-da362617885b)

**Comment by nchamo** [comment]
Fixed by https://github.com/decentraland/catalyst/pull/428
