### ISSUE TITLE
Add special header to all catalyst requests

### ISSUE THREAD

**Issue by menduz** [decentraland/catalyst#453]
To filter better in WAF software. Requests are currently setting the user agent, it is missing in the lambdas (/explore)

**Comment by agusaldasoro** [comment]
The latest version of the catalyst client includes this header, replacing all the requests with that version should resolve this issue. Check if somewhere the catalyst client is not being used.

**Comment by menduz** [comment]
How important/urgent is this issue? Can we move it to the backlog?

**Comment by nchamo** [comment]
Some of the current catalyst owners have expressed that this is important for them
