### ISSUE TITLE
Store last seen at DCL to use it in GC

### ISSUE THREAD

**Issue by agusaldasoro** [decentraland/catalyst#483]
As part of garbage collecting the profiles from the Content Server, we need to store the data from last seen online so we can order by that field when deleting profiles, then we can ensure that the most recent login users' profiles don't get erased.

**Comment by nchamo** [comment]
We should probably close this, since we can use the entity's timestamp for this.

**Comment by menduz** [comment]
In that case, is it "last seen" or "last time they changed something in the profile"?

**Comment by nchamo** [comment]
Whatever it is, if you store it on the profile when it happens, then it will have almost identical timestamp as the entity timestamp. Right?

**Comment by menduz** [comment]
That implies a deployment per visit, we may want to avoid it? I think the point of storing the "last seen" is to garbage collect without making deployments. @agusaldasoro could you expand on the use case?

**Comment by nchamo** [comment]
Oh, I understood that the idea was to include that information in the profile itself, by making deployment when the user logs in.

**Comment by agusaldasoro** [comment]
Storing that information in the profile itself is one possible solution, that would have the disadvantage of having to deploy each time a user logins. I'm going to fix the description as it establishes that the information "last seen online" will be stored in the content server and that is something that we haven't defined yet.

Anyway, this data is something that we want to collect but we need to discuss the prioritization of this particular issue, as there would be other issues for GC profiles that could be more urgent.

**Comment by agusaldasoro** [comment]
This may not be necessary to solve https://github.com/decentraland/catalyst/issues/464, I'm closing it.
