### ISSUE TITLE
Support "deleting" pointers

### ISSUE THREAD

**Issue by nchamo** [decentraland/catalyst#524]
The content server is an append-only database that has the concept of entities and pointers. Right now, once a pointer points to an entity, it can point to new entities but it can't go back to pointing nowhere. Since entities can't be deleted, it might be useful to have this option.

A possible idea would be to have the metadata of the new entity specify that it is not a normal deployment, and that it is meant to make the pointer point nowhere.

If we go with the option above, the expected behaviour could be something like:
* When a deployment of this kind is made, then the previous deployments are marked as overwritten by this new deployment
* This new type of deployment will also be marked as overwritten with any subsequent deployment
* When asked about active entities/deployments, the pointer should return nothing
* When asked about all deployments (not only active), the pointer should include the "delete" deployment

**Comment by agusaldasoro** [comment]
This is not a needed use case for the catalysts to support
