### ISSUE TITLE
Roadmap for other supported blockchains?

### ISSUE THREAD

**Issue by laurencefass** [decentraland/catalyst#543]
Ethereum is cool but slow and expensive. Does Decentraland plan to provide MANA transactions across other (next-gen, faster) blockchains in the future?

Do you have a separate Q&A addressing questions like this?

Thanks

**Comment by nchamo** [comment]
Hey @laurencefass !

If you have questions, then the best place to get answers might be the discord server.

**Comment by nchamo** [comment]
Hey @laurencefass !

If you have questions, then the best place to get answers might be the [discord server](https://dcl.gg/discord).

Now, onto your specific question about MANA, you can already have MANA on Polygon. It is currently used for buying wearables that are also on Polygon. You can send MANA from/to Polygon [here](https://account.decentraland.org/)

**Comment by laurencefass** [comment]
thanks for the intro and links ill head over to discord server for further info.
