### ISSUE TITLE
Create Content-Server API spec using OAS

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#582]
In order to support our internal teams and the community to contribute and support our services we need to be able to provide clear information about our APIs and how to use them. 

OpenAPI Specification https://swagger.io/specification/

Current API Spec 
https://github.com/decentraland/catalyst/blob/master/docs/content-server-api/CONTENT_SERVER_API.md

Please consider adding this for each endpoint 
- Clear explanation of the endpoint
- Examples
- Specific status codes and errors
- Auth method
- Parameters explanations

**Comment by menduz** [comment]
This may be useful https://github.com/decentraland/nft-schema it validates some things from the spec to make it compliant in the CI and it also generates Typescript definitions out of it
