### ISSUE TITLE
Avatars cannot see each other in Aetheria parcels >150 N or >150 E

### ISSUE THREAD

**Issue by cfravel** [decentraland/catalyst#605]
If an avatar is in an Aetheria district parcel north of 150 or east of 150, they cannot be seen by other avatars.
See example in :
[https://youtu.be/nYqdVWOLFz8](https://youtu.be/nYqdVWOLFz8)

This is causing issues for the Aetheria contributor/tenant community.

**Comment by paladinnextgen** [comment]
Any update on the progress?  I see you have found the problem with the bug.  I just moved into this region and have been looking forward to developing in the DCL metaverse.  The multiplayer aspect is critical, and not being able to see avatars in this region is a huge issue that hopefully will be resolved ASAP.  There's about 2000 plots in this area and my neighbors too experience this same issue and is holding back all of us.  Thanks for addressing this.

**Comment by pablitar** [comment]
Hi @paladinnextgen! A fix has been merged to master. See here: https://github.com/decentraland/explorer/commit/4c5877e51de8244d98c4f62a7581babaf3812a52

We are in the middle of a change in repositories and processes, so it may take a little while to see it in production. The target date is August 18th. See here: https://github.com/decentraland/explorer-technical-backlog/issues/23

Thanks for your patience!

**Comment by OK11d** [comment]
Going well?

**Comment by pablitar** [comment]
@OK11d 

In production! It should work now :). Let me know if anything comes up.

**Comment by OK11d** [comment]
NO

**Comment by OK11d** [comment]
Still can't see each other

**Comment by pablitar** [comment]
@OK11d Please ensure you and the other person you are not seeing are in the same realm.

Also, try to clear cache of the browser to ensure that the latest version of the client is loaded.

If that doesn't solve the issue, please provide the coordinates which are having troubles so we can try to reproduce the issue.

Thanks!

**Comment by cfravel** [comment]
I have tested it north of 151 in Aetheria, with two accounts.
They can see each other
THanks!!!!!
