### ISSUE TITLE
Add cache for lambdas/profiles endpoint

### ISSUE THREAD

**Issue by pablitar** [decentraland/catalyst#667]
In Lambdas server, profiles is currently one of the most expensive endpoints:
![image](https://user-images.githubusercontent.com/2048532/134963040-d3d3761c-60f2-430c-91b9-6bee01ca06ff.png)

This is also one of the endpoints that we can't cache in Cloudflare or similar.

We can, though, implement an in-memory cache or similar that fetches the entity from content server and sees if the timestamp has been updated since last time. If not, it can return the cached entity and avoid the expensive calculations that follow. If changed, it can invalidate and recalculate.

**Comment by menduz** [comment]
There is an easier solution, with caché control `Cache-Control: s-maxage=120,max-age=120,public` makes the content cache-able both by the client and by the intermediate mediators (like Cloudflare). That would not make the statistic smaller, but will definitely help reduce the number of times the endpoint is called.

I strongly recommend to first apply the headers and after a week of measurements evaluate if a cache component is really needed.
