### ISSUE TITLE
When you restart a Catalyst keep comms state

### ISSUE THREAD

**Issue by abarmat** [decentraland/catalyst#67]
Whenever you restart a Catalyst server, for example let say you are updating to a new version you lose all comms connections and the server name is changed.

Maybe some form of state can be persisted, for example the comm server name, so clients can retry reaching out to the server when the server is back online.

**Comment by pablitar** [comment]
@moliva is working on solving this from the client side. But eventually we may want to still add persistance to avoid having to rebuild the whole state.

**Comment by nchamo** [comment]
Hey @pablitar !

I think we can close this now, right?

I think this was fixed by https://github.com/decentraland/catalyst/commit/55804f32300aaacb9d6b87baa86e96bc7bc3c0ff, right?

**Comment by pablitar** [comment]
I think we can.

There is still the idea of persisting the whole state. But for now we can get away with the name and the retries from client side.

We could follow up in a separate issue if we think there is a reason to do that. But I can't think of one yet.

Closing!
