### ISSUE TITLE
Running Catalyst / OnServer: Error 1 / OnLocalPC: Warning&Error1 🤔🤔

### ISSUE THREAD

**Issue by loveTSloveNET** [decentraland/catalyst#772]
Hello Sir! 🙂

Just testing and understanding around better the tech.
On this repo:
[https://github.com/decentraland/catalyst](https://github.com/decentraland/catalyst)

![image](https://user-images.githubusercontent.com/24850331/142733769-22815397-ebfa-4d8a-8e23-a329cbbda497.png)

**PROBLEM:**
I have tried to run it on myserver Ubuntu 20.4 and on my LocalPC Windows 10, and am getting this results:

SERVER: Ubuntu 20.4
`cd /var/www/catalyst`
`yarn install`
`yarn build // error 1`
![image](https://user-images.githubusercontent.com/24850331/142733861-f679d9c4-85eb-4002-98a9-3d42bed2cdc3.png)

`yarn test // error 1`
![image](https://user-images.githubusercontent.com/24850331/142733988-32450609-c1d9-4e95-9674-99299b3b6ac7.png)

LOCAL PC: Windows 10
`yarn install`
`yarn build // No license field?`
![image](https://user-images.githubusercontent.com/24850331/142734146-b4c3fbc7-6b48-4538-905b-d5068fa5b637.png)

`yarn test // error 1`
![image](https://user-images.githubusercontent.com/24850331/142734173-f24dc18b-dd5d-472e-950f-6158d2a80676.png)

QUESTION:
Any hint on what is the problem?
Is it important the "No license field"? If so, were do i find it?

Thanks! 😎🙏

**Comment by agusaldasoro** [comment]
Please try again with the latest version and if the issue persists then please open another ticket. thanks!
