### ISSUE TITLE
Running ContentServer / How much memory?

### ISSUE THREAD

**Issue by loveTSloveNET** [decentraland/catalyst#773]
Hello Sir! 🙂

It runs fine on my LocalPC Windows 10.
On the test server I run out of memory.

What should be the minimum requirements to run this ContentServer?

And what represents all this verbose? Is it 3D objects?
![image](https://user-images.githubusercontent.com/24850331/142734788-175da4da-d106-4d52-bc05-9504b969963c.png)

Thanks

**Comment by pentreathm** [comment]
Hi @loveTSloveNET 
The recommended HW requirements are: 32 GiB, 8 vCPU, 512 SSD.  
Please if you have questions, go to Discord.
