### ISSUE TITLE
Runing Lambdas / OnServer: Error 1 / OnLocalPC: Error 1

### ISSUE THREAD

**Issue by loveTSloveNET** [decentraland/catalyst#774]
Hello Sir! 🙂

I run both ContentServer and LightHouse fine.
But with Lambdas i get this error:

SERVER: Ubuntu 20.4
```
cd /var/www/catalyst/lambdas
yarn install
yarn build // I recive a "No license field" warning
```
![image](https://user-images.githubusercontent.com/24850331/142735000-da03a324-7ac2-42ca-a3d0-e88ecac3d58f.png)

```
yarn start
// error 1 (Cannot read properties of undefined (reading 'toLowerCase')

```
![image](https://user-images.githubusercontent.com/24850331/142735059-b883599b-1720-421f-8f7a-a3bcdeb11c22.png)

LOCAL PC: Windows 10
```
yarn install
yarn build
yarn start
```
![image](https://user-images.githubusercontent.com/24850331/142735176-45782562-8099-4cd7-a720-1746356cccb4.png)

Any hint?
Thanks! 😎🙏

**Comment by agusaldasoro** [comment]
Please try again with the latest version and if this issue persists, then open another issue. Thanks!
