### ISSUE TITLE
Running PoW / What happened to PoW? Is it deprecrated?

### ISSUE THREAD

**Issue by loveTSloveNET** [decentraland/catalyst#775]
Hello Sir! 🙂

Was reading the readme.md file
![image](https://user-images.githubusercontent.com/24850331/142735255-989556e3-170d-4d93-89b9-5e46ea82d1c0.png)

And seems this link is death:
https://github.com/decentraland/pow-authorization-server

What happened to PoW?
Is it deprecrated?

Thanks! 😎🙏

**Comment by menduz** [comment]
It is no longer used and soon to be deprecated. I made the repository public.
