### ISSUE TITLE
@catalyst/commons npm module not found

### ISSUE THREAD

**Issue by petrukovichmark** [decentraland/catalyst#937]
when trying to install npm module, '@catalyst/commons@0.1.0' is not on npm registry.

**Comment by agusaldasoro** [comment]
Hi @petrukovichmark what command are you running? That is a local build from https://github.com/decentraland/catalyst/blob/main/commons/package.json

If you want to run the Content server locally, then you need to run: https://github.com/decentraland/catalyst/tree/main/content#how-to-run-it

For lambdas: https://github.com/decentraland/catalyst/tree/main/lambdas#how-to-run-it

For comms: https://github.com/decentraland/catalyst/tree/main/comms/lighthouse#set-up

**Comment by petrukovichmark** [comment]
cool, thanks

**Comment by petrukovichmark** [comment]
Hi, @agusaldasoro 
I got error when launching lambdas server as below

```
Starting lambdas server...
Can not start Lambdas server:  TypeError: Cannot read property 'toLowerCase' of undefined
```
