### ISSUE TITLE
Unexpected end of JSON input: empty entity file while synchronizing

### ISSUE THREAD

**Issue by guidota** [decentraland/catalyst#947]
## Description 

An entity file can be corrupted while synchronizing and it is stored as empty, causing a failed deployment.

<img width="988" alt="Screen Shot 2022-03-01 at 09 45 22" src="https://user-images.githubusercontent.com/7695773/156190360-2d55fa0c-4554-451d-bb3b-bf1a503423df.png">

In this example, the file is empty and it will never recover from this situation, we must add a mechanism to validate the entity before storing it. Using a temporal file before validating will prevent it but we also need to be sure all communication channels are working as expected or it is a parsing issue.

**Comment by agusaldasoro** [comment]
This is currently done when syncing entities between catalyst, but it's missing when making an organic deployment.
