### ISSUE TITLE
Improve concurrent requests performance

### ISSUE THREAD

**Issue by guidota** [decentraland/catalyst#963]
Some endpoints like `/entities` use a cache to keep LRU entities but it is not effective when more than one request are querying the same ids or pointers.

We should add certain logic with promises to avoid multiple calls to the DB for same ids/pointers.

**Comment by marianogoldman** [comment]
Discussed with the team on how to solve this. There's no simple solution to the current behavior. Complex solution would be some sort of serialization of the requests, where each request queries the DB for entities it **needs and that it's not being currently fetched by other requests**. Whatever comes next removes other entity ids already queried in prior ones. But then, it's another complex problem what to do in case a query finishes before the prior ones. Should it wait? On which ones?

This service is already clever enough to get from DB the cache misses. As soon as entities are fetch they're added to the cache. So it's very efficient already.

The access pattern we would normally see here doesn't seem to be a problem as it is. And, as per [the dashboard](https://grafana.decentraland.systems/d/mN-oXzB7z/active-entities-cache?orgId=1&from=now-30d&to=now), the cache seems to be doing a good job.

So closing this as as not an issue currently and the solution could be worse than the current behavior.
