### ISSUE TITLE
Can't run unit tests without docker

### ISSUE THREAD

**Issue by menduz** [decentraland/catalyst#975]
The command is 
```
~/code/catalyst/content chore/identity-fix  nvm ❭ yarn run test -t ContentCluster
```

![Screen Shot 2022-01-17 at 11 11 22](https://user-images.githubusercontent.com/260114/149785273-4ce2a89b-9038-461d-9557-fa9caae41eb4.png)

**Comment by guidota** [comment]
fixed on #847
